import { vi } from 'vitest'

// Stub for virtual:pwa-register/react generated by vite-plugin-pwa
export function useRegisterSW() {
  return {
    needRefresh: [false, vi.fn()] as [boolean, ReturnType<typeof vi.fn>],
    offlineReady: [false, vi.fn()] as [boolean, ReturnType<typeof vi.fn>],
    updateServiceWorker: vi.fn(),
  }
}
